/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        /** Upsert Profile */
        post: operations["upsert_profile_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_knowledge_assets_get"];
        put?: never;
        /** Upload Assets */
        post: operations["upload_assets_api_knowledge_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Asset */
        delete: operations["delete_asset_api_knowledge_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/assets/{asset_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Asset */
        post: operations["retry_asset_api_knowledge_assets__asset_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Assets */
        get: operations["search_assets_api_knowledge_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Plan */
        get: operations["get_current_plan_api_plans_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Plan */
        post: operations["generate_plan_api_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Plan */
        post: operations["activate_plan_api_plans__plan_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/assistant/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan Assistant Session */
        post: operations["create_plan_assistant_session_api_plans_assistant_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/assistant/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Plan Assistant Message */
        post: operations["send_plan_assistant_message_api_plans_assistant_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/assistant/sessions/{session_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Plan From Assistant */
        post: operations["generate_plan_from_assistant_api_plans_assistant_sessions__session_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan Detail */
        get: operations["get_plan_detail_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        /** Delete Plan */
        delete: operations["delete_plan_api_plans__plan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalculate Plan */
        post: operations["recalculate_plan_api_plans__plan_id__recalculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_api_learning_session_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/session/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_learning_session_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/session/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Session */
        post: operations["complete_session_api_learning_session_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_api_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Assessment */
        post: operations["generate_assessment_api_assessments_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Assessment */
        post: operations["submit_assessment_api_assessments__assessment_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment Result */
        get: operations["get_assessment_result_api_assessments__assessment_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Workflow */
        get: operations["get_current_workflow_api_workflow_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Workflow */
        post: operations["advance_workflow_api_workflow_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/proceed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Proceed Workflow */
        post: operations["proceed_workflow_api_workflow_proceed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Assessment */
        Assessment: {
            /** Id */
            id: string;
            type: components["schemas"]["AssessmentType"];
            /** Scope */
            scope: string;
            /** Linked Plan Id */
            linked_plan_id: string;
            /** Questions */
            questions?: components["schemas"]["Question"][];
            /** Difficulty */
            difficulty: string;
            status: components["schemas"]["AssessmentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AssessmentGenerateRequest */
        AssessmentGenerateRequest: {
            /** Linked Plan Id */
            linked_plan_id: string;
            /** @default checkpoint */
            type: components["schemas"]["AssessmentType"];
        };
        /**
         * AssessmentStatus
         * @enum {string}
         */
        AssessmentStatus: "generated" | "submitted" | "evaluated";
        /** AssessmentSubmitRequest */
        AssessmentSubmitRequest: {
            /** Answers */
            answers?: components["schemas"]["SubmissionAnswer"][];
            /** Uncertainties */
            uncertainties?: string[];
        };
        /** AssessmentSubmitResponse */
        AssessmentSubmitResponse: {
            submission: components["schemas"]["Submission"];
            evaluation: components["schemas"]["Evaluation"];
        };
        /**
         * AssessmentType
         * @enum {string}
         */
        AssessmentType: "checkpoint" | "unit" | "final";
        /** Body_upload_assets_api_knowledge_assets_post */
        Body_upload_assets_api_knowledge_assets_post: {
            /** Files */
            files: string[];
            /** Title */
            title?: string | null;
            /** Tags */
            tags?: string | null;
        };
        /** ChunkSearchResult */
        ChunkSearchResult: {
            /** Asset Id */
            asset_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            /** Score */
            score: number;
        };
        /** ConversationTurn */
        ConversationTurn: {
            /** Role */
            role: string;
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CurrentPlanResponse */
        CurrentPlanResponse: {
            macro_plan?: components["schemas"]["MacroPlan"] | null;
            current_micro_plan?: components["schemas"]["MicroPlan"] | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** Evaluation */
        Evaluation: {
            /** Id */
            id: string;
            /** Submission Id */
            submission_id: string;
            /** Score */
            score: number;
            /** Earned Points */
            earned_points: number;
            /** Total Points */
            total_points: number;
            /** Score Ratio */
            score_ratio: number;
            /** Passed */
            passed: boolean;
            /** Feedback */
            feedback: string;
            /** Mistake Analysis */
            mistake_analysis?: {
                [key: string]: unknown;
            }[];
            /** Recommendations */
            recommendations?: string[];
            /** Question Results */
            question_results?: components["schemas"]["QuestionResult"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnowledgeAsset */
        KnowledgeAsset: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** File Type */
            file_type: string;
            /** File Size Bytes */
            file_size_bytes: number;
            status: components["schemas"]["KnowledgeAssetStatus"];
            parse_error_reason?: components["schemas"]["ParseErrorReason"] | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /** Raw Path */
            raw_path: string;
            /**
             * Parsed Text
             * @default
             */
            parsed_text: string;
            /** Tags */
            tags?: string[];
            /** Chunks */
            chunks?: components["schemas"]["KnowledgeChunk"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** KnowledgeAssetListResponse */
        KnowledgeAssetListResponse: {
            /** Assets */
            assets: components["schemas"]["KnowledgeAsset"][];
        };
        /**
         * KnowledgeAssetStatus
         * @enum {string}
         */
        KnowledgeAssetStatus: "uploading" | "parsing" | "indexing" | "ready" | "parse_failed";
        /** KnowledgeChunk */
        KnowledgeChunk: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Embedding Id */
            embedding_id?: string | null;
        };
        /** KnowledgeSearchResponse */
        KnowledgeSearchResponse: {
            /** Chunks */
            chunks: components["schemas"]["ChunkSearchResult"][];
        };
        /** LearningSession */
        LearningSession: {
            /** Id */
            id: string;
            /** Micro Plan Id */
            micro_plan_id: string;
            /** Session Summary */
            session_summary: string;
            /** Conversation Turns */
            conversation_turns?: components["schemas"]["ConversationTurn"][];
            /** Completion Signals */
            completion_signals?: string[];
            /** Mastery Signals */
            mastery_signals?: string[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LearningSessionCompleteRequest */
        LearningSessionCompleteRequest: {
            /** Session Id */
            session_id: string;
            /** Completion Signals */
            completion_signals?: string[];
        };
        /** LearningSessionMessageRequest */
        LearningSessionMessageRequest: {
            /** Session Id */
            session_id: string;
            /** Message */
            message: string;
            /** Preferred Style */
            preferred_style?: string | null;
        };
        /** LearningSessionMessageResponse */
        LearningSessionMessageResponse: {
            /** Reply */
            reply: string;
            /** Session Summary */
            session_summary: string;
            /** Mastery Signals */
            mastery_signals?: string[];
        };
        /** LearningSessionStartRequest */
        LearningSessionStartRequest: {
            /** Micro Plan Id */
            micro_plan_id: string;
        };
        /** MacroPlan */
        MacroPlan: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Title */
            title: string;
            /** Goal */
            goal: string;
            /** Duration */
            duration: {
                [key: string]: string | number;
            };
            /** Milestones */
            milestones?: {
                [key: string]: unknown;
            }[];
            /** Units */
            units?: {
                [key: string]: unknown;
            }[];
            status: components["schemas"]["PlanStatus"];
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** MicroPlan */
        MicroPlan: {
            /** Id */
            id: string;
            /** Macro Plan Id */
            macro_plan_id: string;
            /** Unit Id */
            unit_id: string;
            /** Title */
            title: string;
            /** Topics */
            topics?: string[];
            /** Estimated Duration */
            estimated_duration: number;
            /** Tasks */
            tasks?: {
                [key: string]: unknown;
            }[];
            /** Completion Criteria */
            completion_criteria?: string[];
            /** Assessment Trigger */
            assessment_trigger: {
                [key: string]: string | number;
            };
            status: components["schemas"]["PlanStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ParseErrorReason
         * @enum {string}
         */
        ParseErrorReason: "unsupported_format" | "file_corrupted" | "empty_content";
        /** PlanAssistantGenerateResponse */
        PlanAssistantGenerateResponse: {
            session: components["schemas"]["PlanAssistantSession"];
            macro_plan: components["schemas"]["MacroPlan"];
            current_micro_plan: components["schemas"]["MicroPlan"];
        };
        /** PlanAssistantMessageRequest */
        PlanAssistantMessageRequest: {
            /** Message */
            message: string;
        };
        /** PlanAssistantMessageResponse */
        PlanAssistantMessageResponse: {
            /** Reply */
            reply: string;
            session: components["schemas"]["PlanAssistantSession"];
        };
        /** PlanAssistantSession */
        PlanAssistantSession: {
            /** Id */
            id: string;
            /** Conversation Turns */
            conversation_turns?: components["schemas"]["ConversationTurn"][];
            /** Conversation Summary */
            conversation_summary: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlanCardSummary */
        PlanCardSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Goal */
            goal: string;
            status: components["schemas"]["PlanStatus"];
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Unit Count */
            unit_count: number;
            /** Completed Unit Count */
            completed_unit_count: number;
            /** Progress Percent */
            progress_percent: number;
            /** Current Micro Plan Id */
            current_micro_plan_id?: string | null;
            /** Current Micro Plan Title */
            current_micro_plan_title?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
        };
        /** PlanDetailResponse */
        PlanDetailResponse: {
            macro_plan: components["schemas"]["MacroPlan"];
            /** Micro Plans */
            micro_plans?: components["schemas"]["MicroPlan"][];
            /** Current Micro Plan Id */
            current_micro_plan_id?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
        };
        /** PlanGenerateRequest */
        PlanGenerateRequest: {
            /** Learning Goals */
            learning_goals: string;
            /** Time Budget */
            time_budget: {
                [key: string]: string | number;
            };
            /** Current Level */
            current_level: string;
            /** Preferred Style */
            preferred_style: string;
            /** Preferred Difficulty */
            preferred_difficulty: string;
            /** Preferred Question Types */
            preferred_question_types?: string[];
            /** Attached Asset Ids */
            attached_asset_ids?: string[];
        };
        /** PlanGenerateResponse */
        PlanGenerateResponse: {
            macro_plan: components["schemas"]["MacroPlan"];
            current_micro_plan: components["schemas"]["MicroPlan"];
        };
        /** PlanListResponse */
        PlanListResponse: {
            /** Plans */
            plans?: components["schemas"]["PlanCardSummary"][];
        };
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "draft" | "active" | "completed";
        /** Question */
        Question: {
            /** Id */
            id: string;
            /** Assessment Id */
            assessment_id: string;
            /** Question Type */
            question_type: string;
            /** Stem */
            stem: string;
            /** Options */
            options?: string[];
            /** Reference Scope */
            reference_scope: string;
            /** Expected Competency */
            expected_competency: string;
            /** Points */
            points: number;
            /** Explanation */
            explanation?: string | null;
            /** Rubric */
            rubric?: components["schemas"]["RubricCriterion"][];
        };
        /** QuestionResult */
        QuestionResult: {
            /** Question Id */
            question_id: string;
            /** Question Type */
            question_type: string;
            /** Submitted Answer */
            submitted_answer: string;
            /** Earned Points */
            earned_points: number;
            /** Max Points */
            max_points: number;
            /** Is Correct */
            is_correct?: boolean | null;
            /** Correct Answer */
            correct_answer?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Error Reason */
            error_reason?: string | null;
            /** Rubric Results */
            rubric_results?: components["schemas"]["RubricResult"][];
        };
        /** RubricCriterion */
        RubricCriterion: {
            /** Criterion */
            criterion: string;
            /** Points */
            points: number;
            /** Keywords */
            keywords?: string[];
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** RubricResult */
        RubricResult: {
            /** Criterion */
            criterion: string;
            /** Earned Points */
            earned_points: number;
            /** Max Points */
            max_points: number;
            /** Feedback */
            feedback: string;
        };
        /** Submission */
        Submission: {
            /** Id */
            id: string;
            /** Assessment Id */
            assessment_id: string;
            /** Answers */
            answers?: components["schemas"]["SubmissionAnswer"][];
            /** Uncertainties */
            uncertainties?: string[];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** SubmissionAnswer */
        SubmissionAnswer: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Learning Goals */
            learning_goals: string;
            /** Subject Scope */
            subject_scope: string;
            /** Current Level */
            current_level: string;
            /** Time Budget */
            time_budget: {
                [key: string]: string | number;
            };
            /** Preferred Style */
            preferred_style: string;
            /** Preferred Difficulty */
            preferred_difficulty: string;
            /** Preferred Question Types */
            preferred_question_types?: string[];
            /**
             * Behavior Summary
             * @default
             */
            behavior_summary: string;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserProfileCreate */
        UserProfileCreate: {
            /** Learning Goals */
            learning_goals: string;
            /** Subject Scope */
            subject_scope: string;
            /** Current Level */
            current_level: string;
            /** Time Budget */
            time_budget: {
                [key: string]: string | number;
            };
            /** Preferred Style */
            preferred_style: string;
            /** Preferred Difficulty */
            preferred_difficulty: string;
            /** Preferred Question Types */
            preferred_question_types?: string[];
            /**
             * Behavior Summary
             * @default
             */
            behavior_summary: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowAdvanceRequest */
        WorkflowAdvanceRequest: {
            next_stage: components["schemas"]["WorkflowStage"];
            /** Reason */
            reason: string;
        };
        /**
         * WorkflowStage
         * @enum {string}
         */
        WorkflowStage: "onboarding" | "planning" | "learning" | "checkpoint_test" | "unit_review" | "unit_test" | "final_review" | "final_test" | "next_cycle";
        /** WorkflowState */
        WorkflowState: {
            /** Id */
            id: string;
            current_stage: components["schemas"]["WorkflowStage"];
            /** Current Macro Plan Id */
            current_macro_plan_id?: string | null;
            /** Current Micro Plan Id */
            current_micro_plan_id?: string | null;
            /** Recent Assessment Id */
            recent_assessment_id?: string | null;
            /** Next Action */
            next_action: string;
            /** Stage History */
            stage_history?: {
                [key: string]: unknown;
            }[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upsert_profile_api_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_knowledge_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeAssetListResponse"];
                };
            };
        };
    };
    upload_assets_api_knowledge_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_assets_api_knowledge_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeAssetListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_knowledge_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_asset_api_knowledge_assets__asset_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeAsset"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_assets_api_knowledge_search_get: {
        parameters: {
            query: {
                query: string;
                topK?: number;
                tags?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanListResponse"];
                };
            };
        };
    };
    get_current_plan_api_plans_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentPlanResponse"];
                };
            };
        };
    };
    generate_plan_api_plans_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanGenerateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_plan_api_plans__plan_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentPlanResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_assistant_session_api_plans_assistant_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanAssistantSession"];
                };
            };
        };
    };
    send_plan_assistant_message_api_plans_assistant_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanAssistantMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanAssistantMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_from_assistant_api_plans_assistant_sessions__session_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanAssistantGenerateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_detail_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recalculate_plan_api_plans__plan_id__recalculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanGenerateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_learning_session_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningSessionStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSession"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_learning_session_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningSessionMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_learning_session_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningSessionCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_api_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_assessment_api_assessments_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_assessment_api_assessments__assessment_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentSubmitResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_result_api_assessments__assessment_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evaluation"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_workflow_api_workflow_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
        };
    };
    advance_workflow_api_workflow_advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowAdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proceed_workflow_api_workflow_proceed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
